name: designpension_wernigerode
description: Übernachten in Design-Pensionen

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ">=2.6.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  webview_flutter: ^3.0.4
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.3
  font_awesome_flutter: ^10.4.0
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_app_name: ^0.1.0
  flutter_lints: ^2.0.1 

flutter_app_name:
  name: "Designpensionen Wernigerode"

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher.png"
  remove_alpha:ios: "true"
  
flutter_native_splash:
  color: "#000000"
  image: "assets/launcher.png"
  android_gravity: center
  ios_content_mode: center